/**
 * Compact seed: 100+ categorized document templates for SAID
 */
import { PC_REPAIR_QUOTE_TEMPLATES } from './templates/pcRepairQuotes.js'

const baseStyle = `body{font-family:system-ui,sans-serif;color:#0f172a;padding:36px;max-width:820px;margin:0 auto;font-size:14px;line-height:1.5}
.brand{color:#007A4D;font-weight:800;letter-spacing:.08em;font-size:11px;text-transform:uppercase}
h1{margin:.35rem 0 1rem;font-size:24px}h2{font-size:16px;margin:1.2rem 0 .5rem;color:#007A4D}
.box{border:1px solid #e2e8f0;border-radius:10px;padding:14px;margin:10px 0}.muted{color:#64748b;font-size:12px}
.row{display:flex;justify-content:space-between;gap:12px;margin:6px 0;border-bottom:1px solid #f1f5f9;padding-bottom:6px}
.total{font-size:20px;font-weight:800;color:#007A4D}table{width:100%;border-collapse:collapse;margin:12px 0}
th,td{border:1px solid #e2e8f0;padding:8px;text-align:left}th{background:#f8fafc;font-size:12px}
.sig{margin-top:40px;display:flex;gap:40px}.sig div{flex:1;border-top:1px solid #94a3b8;padding-top:8px;font-size:12px}
.badge{display:inline-block;background:#007A4D;color:#fff;padding:2px 8px;border-radius:6px;font-size:11px;font-weight:700}
.footer{margin-top:32px;font-size:11px;color:#94a3b8;border-top:1px solid #e2e8f0;padding-top:12px}`

function wrap(title, body) {
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><style>${baseStyle}</style></head><body>
  <div class="brand">SA Invoice Desk</div><h1>${title}</h1>${body}
  <div class="footer">Generated by SAID · {{company_name}} · {{company_address}} · {{company_phone}}</div>
  </body></html>`
}

const defs = [
  ['invoice_cover','Tax invoice cover','Invoicing','all','Tax invoice summary','<div class="box"><div class="muted">Bill to</div><strong>{{client_name}}</strong><br>{{client_address}}</div><div class="box"><div class="muted">Amount due</div><div class="total">R {{amount_due}}</div><p class="muted">Invoice {{invoice_number}} · Due {{due_date}}</p></div><p>{{payment_note}}</p>'],
  ['tax_invoice_full','Full tax invoice','Invoicing','all','Detailed SA tax invoice','<div class="row"><span>Invoice #</span><strong>{{invoice_number}}</strong></div><div class="row"><span>Date</span><span>{{invoice_date}}</span></div><div class="box"><strong>{{client_name}}</strong><br>{{client_address}}</div><table><thead><tr><th>Description</th><th>Qty</th><th>Price</th><th>Total</th></tr></thead><tbody>{{line_items_html}}</tbody></table><div class="row"><span>Subtotal</span><span>R {{exclusive}}</span></div><div class="row"><span>VAT</span><span>R {{vat_amount}}</span></div><div class="row"><span class="total">Total</span><span class="total">R {{total}}</span></div>'],
  ['proforma_invoice','Proforma invoice','Invoicing','all','Proforma quotation','<span class="badge">PROFORMA</span><div class="box"><strong>{{client_name}}</strong></div><table><thead><tr><th>Item</th><th>Qty</th><th>Amount</th></tr></thead><tbody>{{line_items_html}}</tbody></table><div class="total">R {{total}}</div>'],
  ['credit_note','Credit note','Invoicing','all','Credit note','<span class="badge">CREDIT</span><div class="row"><span>Ref</span><strong>{{invoice_number}}</strong></div><div class="total">R {{amount_due}}</div><p>{{notes}}</p>'],
  ['statement_of_account','Statement of account','Invoicing','all','Balance statement','<div class="box"><strong>{{client_name}}</strong></div><table><thead><tr><th>Date</th><th>Ref</th><th>Debit</th><th>Credit</th></tr></thead><tbody>{{line_items_html}}</tbody></table><div class="total">Balance R {{amount_due}}</div>'],
  ['receipt','Payment receipt','Invoicing','all','Payment receipt','<div class="box">From {{client_name}}</div><div class="total">R {{amount_due}}</div><div class="row"><span>Method</span><span>{{payment_method}}</span></div><div class="row"><span>Date</span><span>{{payment_date}}</span></div>'],
  ['quotation','Quotation','Sales','all','Sales quote','<div class="box"><strong>{{client_name}}</strong></div><p class="muted">Valid until {{due_date}}</p><table><thead><tr><th>Description</th><th>Qty</th><th>Total</th></tr></thead><tbody>{{line_items_html}}</tbody></table><div class="total">R {{total}}</div>'],
  ['purchase_order','Purchase order','Procurement','all','PO form','<div class="row"><span>PO #</span><strong>{{po_number}}</strong></div><div class="row"><span>Supplier</span><span>{{supplier_name}}</span></div><table><thead><tr><th>Item</th><th>Qty</th><th>Total</th></tr></thead><tbody>{{line_items_html}}</tbody></table>'],
  ['job_card','Job card','Service','it,pc_repair,msp','Technician job card','<div class="row"><span>Client</span><strong>{{client_name}}</strong></div><div class="row"><span>Site</span><span>{{site_address}}</span></div><div class="row"><span>Technician</span><span>{{technician}}</span></div><div class="row"><span>Devices</span><span>{{devices}}</span></div><h2>Work</h2><p>{{notes}}</p><div class="sig"><div>Client</div><div>Tech</div></div>'],
  ['device_intake','Device intake form','Service','it,pc_repair','PC intake checklist','<div class="row"><span>Client</span><strong>{{client_name}}</strong></div><div class="row"><span>Device</span><span>{{devices}}</span></div><div class="row"><span>Serial</span><span>{{serials}}</span></div><h2>Fault</h2><p>{{notes}}</p><div class="sig"><div>Client</div><div>Staff</div></div>'],
  ['repair_report','Repair completion report','Service','it,pc_repair','Post-repair summary','<div class="row"><span>Job</span><strong>{{job_number}}</strong></div><div class="row"><span>Device</span><span>{{devices}}</span></div><h2>Diagnosis</h2><p>{{diagnosis}}</p><h2>Work done</h2><p>{{notes}}</p><div class="total">R {{total}}</div>'],
]

const catalog = [
  ['sla_report','SLA / Uptime report','Service','it,msp'],
  ['remote_support_log','Remote support log','Service','it,msp'],
  ['asset_handover','Asset handover form','Service','it,pc_repair'],
  ['network_audit','Network audit checklist','Service','it,msp'],
  ['site_instruction','Site instruction','Construction','construction'],
  ['variation_order','Variation order','Construction','construction'],
  ['snag_list','Snag / punch list','Construction','construction'],
  ['material_delivery','Material delivery note','Construction','construction'],
  ['toolbox_talk','Toolbox talk attendance','Construction','construction'],
  ['daily_site_report','Daily site report','Construction','construction'],
  ['engagement_letter','Engagement letter','Professional','consulting,legal'],
  ['timesheet','Timesheet','Professional','consulting,all'],
  ['meeting_minutes','Meeting minutes','Professional','all'],
  ['nda','Non-disclosure agreement','Legal','all'],
  ['service_level_agreement','Service level agreement','Professional','it,consulting'],
  ['proposal','Business proposal','Sales','all'],
  ['delivery_note','Delivery note','Logistics','retail,all'],
  ['goods_received','Goods received note','Logistics','all'],
  ['return_note','Return / RMA note','Logistics','retail,it'],
  ['booking_confirmation','Booking confirmation','Hospitality','hospitality'],
  ['offer_letter','Job offer letter','HR','all'],
  ['payslip_summary','Payslip summary','HR','all'],
  ['leave_application','Leave application','HR','all'],
  ['warning_letter','Disciplinary warning','HR','all'],
  ['patient_intake','Patient intake form','Medical','medical'],
  ['medical_certificate','Medical certificate','Medical','medical'],
  ['treatment_plan','Treatment plan','Medical','medical'],
  ['vehicle_job_card','Vehicle job card','Automotive','automotive'],
  ['vehicle_inspection','Vehicle inspection report','Automotive','automotive'],
  ['lease_summary','Lease summary','Property','property'],
  ['inspection_report','Property inspection','Property','property'],
  ['certificate_of_completion','Certificate of completion','Education','education'],
  ['training_attendance','Training attendance register','Education','education'],
  ['expense_claim','Expense claim','Finance','all'],
  ['petty_cash','Petty cash voucher','Finance','all'],
  ['vat_summary','VAT summary report','Finance','all'],
  ['letterhead','Company letterhead letter','Correspondence','all'],
  ['demand_letter','Payment demand letter','Correspondence','all'],
  ['thank_you_letter','Thank you letter','Correspondence','all'],
  ['work_order','Work order','Service','all'],
  ['checklist','Generic checklist','Operations','all'],
  ['packing_list','Packing list','Logistics','all'],
  ['gate_pass','Gate / visitor pass','Operations','all'],
  ['incident_report','Incident report','Operations','all'],
  ['risk_assessment','Risk assessment','Operations','construction,all'],
  ['method_statement','Method statement','Construction','construction'],
  ['quality_control','QC inspection form','Operations','manufacturing'],
  ['maintenance_log','Maintenance log','Operations','all'],
  ['stock_count','Stock count sheet','Retail','retail'],
  ['price_list','Price list','Sales','all'],
  ['contract_summary','Contract summary','Legal','all'],
  ['change_request','Change request','Professional','all'],
  ['status_report','Project status report','Professional','all'],
  ['rfi','Request for information','Construction','construction'],
  ['warranty_certificate','Warranty certificate','Service','all'],
  ['satisfaction_survey','Customer satisfaction survey','Sales','all'],
  ['referral_letter','Referral letter','Medical','medical'],
  ['consent_form','Consent form','Medical','medical'],
  ['fleet_log','Fleet vehicle log','Automotive','automotive'],
  ['rental_agreement','Equipment rental agreement','Service','all'],
  ['cleaning_checklist','Cleaning checklist','Facilities','property'],
  ['it_onboarding','IT onboarding checklist','Service','it'],
  ['it_offboarding','IT offboarding checklist','Service','it'],
  ['backup_report','Backup verification report','Service','it'],
  ['managed_service_report','Managed services report','Service','msp'],
  ['fire_drill','Fire drill register','Operations','all'],
  ['first_aid_log','First aid treatment log','Operations','all'],
  ['contractor_induction','Contractor induction','Operations','all'],
  ['popi_consent','POPIA consent form','Legal','all'],
  ['bbee_declaration','B-BBEE declaration','Compliance','all'],
  ['director_resolution','Director resolution','Legal','all'],
  ['acknowledgement_debt','Acknowledgement of debt','Legal','all'],
  ['settlement_agreement','Settlement agreement','Legal','all'],
  ['event_runsheet','Event run sheet','Operations','hospitality'],
  ['membership_agreement','Membership agreement','Sales','gym,salon'],
  ['class_register','Class register','Education','education'],
  ['progress_report_student','Student progress report','Education','education'],
  ['parent_consent','Parental consent','Education','education'],
  ['photographer_release','Model / photo release','Legal','marketing'],
  ['waste_manifest','Waste transfer note','Operations','all'],
  ['supplier_eval','Supplier evaluation','Procurement','all'],
  ['rfq','Request for quotation','Procurement','all'],
  ['tender_cover','Tender submission cover','Procurement','all'],
  ['practical_completion','Practical completion certificate','Construction','construction'],
  ['final_completion','Final completion certificate','Construction','construction'],
  ['as_built_register','As-built drawing register','Construction','construction'],
  ['o_and_m_manual','O&M manual cover','Construction','construction'],
  ['hardware_quote','Hardware quotation','Sales','it'],
  ['software_license','Software license certificate','Service','it'],
  ['penetration_summary','Security assessment summary','Service','it'],
  ['calibration_cert','Calibration certificate','Operations','manufacturing,medical'],
  ['bill_of_lading','Bill of lading (simple)','Logistics','all'],
  ['access_control','Access card request','Facilities','property'],
  ['fuel_claim','Fuel claim form','Automotive','automotive'],
  ['lab_request','Lab request form','Medical','medical'],
  ['prescription','Prescription template','Medical','medical'],
  ['dental_chart_summary','Dental treatment summary','Medical','dental'],
  ['vet_consent','Veterinary consent','Medical','veterinary'],
  ['kickoff_agenda','Project kickoff agenda','Professional','all'],
  ['submittal','Submittal form','Construction','construction'],
  ['handover_pack','Project handover pack','Construction','construction'],
  ['retention_release','Retention release request','Construction','construction'],
  ['tax_clearance_req','Tax clearance request','Finance','all'],
  ['shareholder_notice','Shareholder meeting notice','Legal','all'],
  ['loan_agreement_summary','Loan agreement summary','Finance','all'],
  ['suretyship','Suretyship (short)','Legal','all'],
  ['power_of_attorney','Power of attorney (limited)','Legal','all'],
  ['affidavit','Affidavit template','Legal','all'],
  ['agency_agreement','Agency agreement summary','Legal','all'],
  ['distribution_agreement','Distribution agreement summary','Legal','retail'],
  ['sponsorship_proposal','Sponsorship proposal','Sales','marketing'],
  ['catering_order','Catering order form','Hospitality','hospitality'],
  ['room_service','Room / table service docket','Hospitality','hospitality'],
  ['field_trip','Field trip permission','Education','education'],
  ['research_consent','Research participation consent','Education','education,medical'],
  ['music_licence_summary','Music licence summary','Legal','hospitality'],
  ['environmental_incident','Environmental incident','Operations','construction'],
  ['bid_bond_request','Bid bond request','Finance','construction'],
  ['performance_bond','Performance bond summary','Finance','construction'],
]

const genericBody = (label) => `
  <div class="box"><div class="muted">Document</div><strong>${label}</strong></div>
  <div class="row"><span>Reference</span><span>{{reference}}</span></div>
  <div class="row"><span>Date</span><span>{{date}}</span></div>
  <div class="row"><span>Party / Client</span><span>{{client_name}}</span></div>
  <div class="row"><span>Site / Location</span><span>{{site_address}}</span></div>
  <h2>Details</h2><p>{{notes}}</p>
  <div class="sig"><div>Prepared by</div><div>Authorised by</div></div>`

const T = []
for (const d of defs) {
  T.push({ id: d[0], label: d[1], category: d[2], business_types: d[3], description: d[4], html: wrap(d[1], d[5]) })
}
for (const [id, label, category, business_types] of catalog) {
  T.push({ id, label, category, business_types, description: label, html: wrap(label, genericBody(label)) })
}

for (const t of PC_REPAIR_QUOTE_TEMPLATES) {
  T.push({
    id: t.id,
    label: t.label,
    category: t.category,
    business_types: t.business_types,
    description: t.description,
    html: t.html,
  })
}

export const TEMPLATE_SEED = T
export const TEMPLATE_COUNT = T.length
